
server:
  port: 8181

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpa?serverTimezone=Asia/Seoul
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    # ??? ?? ? ?? DB? ?? ???? ??
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    database: mysql # DB ?? ??
  servlet:
    multipart:
      max-file-size: 10MB # 1 개의 파일의 최대 사이즈
      max-request-size: 20MB # 전체 요청의 최대 사이즈

logging.level:
  org.hibernate.SQL: debug

# swagger setting
springdoc:
  swagger-ui:
    path: /myapi.html

jwt:
  secret : 2aJTrVVdIhuHxFZ5sHAtn4SkVO081zfJPtDquWJyxj1GvQ6Ld8ApovOVXw4/Fwr+P70bpLWDggfbztngAAdevQ==

# 업로드 파일 저장 경로
upload:
  path: C:/todo_upload

# s3 접근 설정
aws:
  credentials:
    accessKey: AKIA2KYS3ZZDKWFOBXGV
    secretKey: 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
  region: ap-northeast-2
  bucketName: todo-app-upload-file-bucket799